### ISSUE TITLE
You copied my bot

### ISSUE THREAD

**Issue by Rayzr522** [XeliteXirish/EliteSelfBot#2]
Hey! Someone just told me about your bot, and after looking at the code, it's an almost exact copy of an older version of my bot. I would appreciate some credit or something, obviously I can't force you, but it's sort of "GitHub etiquette". 

_Heck, some of the commands are verbatim from an older version of my bot..._

**Comment by Carbowix** [comment]
Yes, I am a Witness on this Case. Please Just Give him Some Credits, because its Copy Rights My Friend.

It Won't Affect you in something. Just Don't Copy Paste. Try to learn from what he did, so you can do you own.

**Comment by XeliteXirish** [comment]
Severe apologies, a few weeks back I had someone message me on discord asking them to take on their selfbot from their code because they got bored, I didn't realise that it was copy pasted from someone else's! Defiantly wouldn't of started using it then xD Sorry about this mate, I'll stick credit to you on it right away.

**Comment by Rayzr522** [comment]
Thanks! I understand, that's fine :)
